<a href="https://colab.research.google.com/github/jiminkyung/orm/blob/main/python/240119_%EC%95%8C%EA%B3%A0%EB%A6%AC%EC%A6%98_%EB%AC%B8%EC%A0%9C%ED%92%80%EC%9D%B4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### 어제(18일) 연습문제 강사님 답안

In [ ]:
# 풀이 1
def solution(url):
    return url.split('@')[0] + '@weniv.co.kr'

solution('user@weniv.co.kr')

원래 문제 의도는 `user`에 각 이메일 아이디를 넣어 출력해주는거였다 ㅎㅎ

In [1]:
# 변경된 문제의 해답 (원래 의도)
import re

def chagedomain(url):
    return url.split('@')[0] + '@weniv.co.kr'

# 콤마는 의도적으로 넣지 않은 것입니다.
findpattern = re.findall(r"[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Z|a-z]{2,}",
                         "저의 이메일 주소는 kim123@gmail.com입니다."
                         "친구의 이메일 주소는 lee456@gmail.com입니다.")

for url in findpattern:
    print(chagedomain(url))

kim123@weniv.co.kr
lee456@weniv.co.kr


In [ ]:
# 출제 했던 문제의 해답
my_string = "저의 이메일 주소는 kim123@gmail.com입니다. 친구의 이메일 주소는 lee456@gmail.com입니다."
re.sub(r"[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Z|a-z]{2,}", "user@weniv.co.kr", my_string)

# 변경된 문제의 해답
my_string = "저의 이메일 주소는 kim123@gmail.com입니다. 친구의 이메일 주소는 lee456@gmail.com입니다."
re.sub(r"@[A-Za-z0-9.-]+\.[A-Z|a-z]{2,}", "@weniv.co.kr", my_string)

In [ ]:
import re # import와 코드는 보통 2칸


def hello():
    print('world')

따옴표 세개`'''`앞에 f-string 쓸 수 있다;;  
`f'''안녕'''`

# 기본 역량 문제풀이 20문제(프로그래머스 10 + pyalgo 10)

In [2]:
# 코딩 인터뷰 완전분석
# 듣기
# 예제
# 무식하게 풀기
# 최적화
# 검토하기
# 구현하기
# 테스트

## 1번: 짝수/홀수 구하기
https://school.programmers.co.kr/learn/courses/30/lessons/120824

In [3]:
def solution(data):
    홀수 = [i % 2 != 0 for i in data]
    짝수 = [i % 2 == 0 for i in data]
    print(홀수, 짝수)
    return data

solution([1, 2, 3, 4, 5])

[True, False, True, False, True] [False, True, False, True, False]


[1, 2, 3, 4, 5]

In [5]:
# 홀수, 짝수 갯수 구해주기 => 마스킹!!!

def solution(data):
    홀수 = [i % 2 != 0 for i in data]
    짝수 = [i % 2 == 0 for i in data]
    return [sum(짝수), sum(홀수)]

solution([1, 2, 3, 4, 5])

[2, 3]

In [7]:
# 가장 쉬운 풀이
def solution(data):
    count = 0
    for i in data:
        if i % 2 == 0:
            count += 1
    return [count, len(data)-count]
# 정답 제출할땐 solution() 빼줌

In [8]:
# 간지나는 코드 ㄷㄷ
def solution(num_list):
    answer = [0, 0]
    for i in num_list:
        answer[i % 2] += 1
    return answer

In [9]:
# 좋은 풀이는 아닙니다.
# data의 가변 최대치를 봅니다.
def solution(data):
    짝수 = [i % 2 == 0 for i in data]
    return [sum(짝수), len(data) - sum(짝수)] # sum이 순회합니다.

In [10]:
def solution(data):
    짝수 = [i % 2 == 0 for i in data]
    갯수 = sum(짝수)
    return [갯수, len(data) - 갯수]
    # 몇초간의 성능 차이 중요함

## 2번: 머쓱이보다 키큰사람
https://school.programmers.co.kr/learn/courses/30/lessons/120585

In [11]:
# 이렇게 언패킹 해서 사용할 수 있는 것들은 언패킹 해주세요.
# 가독성이 좋아집니다!
def solution(data):
    array, height = data
    pass

solution([[149, 180, 192, 170], 167])

In [13]:
# 정답이지만 가독성이 떨어진다. filter를 사용해보자.
def solution(array, height):
    count = 0
    for i in array:
        if i > height:
            count += 1
    return count

solution([149, 180, 192, 170], 167)

3

In [14]:
def solution(array, height):
    print(list(filter(lambda x: x > height, array)))
    return

solution([149, 180, 192, 170], 167)

[180, 192, 170]


In [19]:
# 이렇게 하고싶겠지만, filter는 len가 없다! => list를 추가해줘야함

def solution(array, height):
    # return len(filter(lambda x: x > height, array)) # error
    return len(list(filter(lambda x:x>height, array)))

solution([149, 180, 192, 170], 167)

# 왜? filter에는 len가 없나요?
# filter는 순회 돌기 전까지 실행이 되지 않은 함수
# for와 같이 순회를 돌아야 그때서야 각 원소별로 접근해서
# 주문만 하고 아직 제조되지 않은 커피
# 커피를 달라고 소리쳐야(순회/형변환) 그때야 제조가 됩니다.

3

In [20]:
def solution(array, height):
    return sum(map(lambda x: x> height, array))

solution([149, 180, 192, 170], 167)
# list 형변환보다 sum이 좀 더 부하가 덜 합니다.

3

In [21]:
# 리스트 컴프리헨션 사용
# n번 돌아야하는 순회인건 같음

# 리스트 컴프리헨션 쓰는것보다 map이나 filter를 쓰는게
# 나중에 읽기엔 가독성이 더 좋다~!

def solution(array, height):
    return sum([i > height for i in array])

solution([149, 180, 192, 170], 167)

3

In [22]:
def solution(array, height):
    return sum(i > height for i in array)

solution([149, 180, 192, 170], 167)

3

## 3번: 숨어있는 숫자의 덧셈
https://school.programmers.co.kr/learn/courses/30/lessons/120851

In [ ]:
# 오답, 그러나 이렇게도 많이 사용합니다.
def solution(my_string):
    count = 0
    for i in my_string:
        if i.isdigit():
            count += 1

solution("aAb1B2cC34oOp")

In [24]:
def solution(my_string):
    result = 0
    for i in my_string:
        if i.isdigit():
            result += int(i)

    return result

solution("aAb1B2cC34oOp")

10

In [26]:
# 효율적이진 않지만, 문법 복습차원에서
def solution(my_string):
    return list(filter(lambda x: x.isdigit(), list(my_string)))

solution("aAb1B2cC34oOp")

['1', '2', '3', '4']

In [28]:
def solution(my_string):
    return list(filter(str.isdigit, list(my_string)))
    # str에 isdigit으로 바로 뽑을수도 있다.

solution("aAb1B2cC34oOp")

['1', '2', '3', '4']

In [31]:
def solution(my_string):
    return list(filter(str.isdigit, my_string))
    # 굳이 list로 형변환해주지 않아도 된다.

solution("aAb1B2cC34oOp")

['1', '2', '3', '4']

In [32]:
# isdigit에 ()가 있고 없고의 차이는 무엇인가요?
# str.isdigit은 string 클래스에서 제공해주고 있는 함수다.
# isdigit()과는 다르다. 직접 전달해준다.
def 함수(x):
    return x.isdigit()

def solution(my_string):
    return list(filter(함수, my_string))

solution("aAb1B2cC34oOp")

['1', '2', '3', '4']

In [33]:
# 효율적이진 않지만, 문법 복습차원에서
def solution(my_string):
    return sum(map(int,(filter(str.isdigit, my_string))))

solution("aAb1B2cC34oOp")

10

In [34]:
# 효율적이진 않지만, 문법 복습차원에서
# 어쨌든 한번에 했죠?
def solution(my_string):
    return sum(map(lambda x: int(x) if x.isdigit() else False, my_string))

solution("aAb1B2cC34oOp")

10

In [38]:
# r은 raw 날것의 라는 뜻이 있어요.
# 실무에서 자주쓰는 용어입니다. raw != low(이 용어는 자주 사용하지 않습니다.)
# raw data를 전달해줘 => 가공하지 않은 순수 데이터를 달라는 얘기입니다.

r'hello\nworld' # \n 이스케이프 문자입니다.
print('r없을때', 'hello\nworld')
print('r있을때', r'hello\nworld')
# 왜요? 정규표현식에서 이스케이프 문자를 많이 사용하니까요!

r없을때 hello
world
r있을때 hello\nworld


In [39]:
import re

re.findall(r'[0-9]', "aAb1B2cC34oOp")

['1', '2', '3', '4']

코딩 == 악기연습  
이론공부만 하지 말고 훈련을 많이 하자 ㅎㅎ

In [40]:
import re


def solution(s):
    return sum(map(int, re.findall(r'[0-9]', s)))

solution("aAb1B2cC34oOp")

10

In [43]:
import re


def solution(s):
    return sum(map(int, (re.sub(r'[a-zA-Z]','',s))))

solution("aAb1B2cC34oOp")

10

## 4번: 암호 해독
https://school.programmers.co.kr/learn/courses/30/lessons/120892

In [44]:
def solution(cipher, code):
    return cipher[code-1::code]

solution("dfjardstddetckdaccccdegk", 4)

'attack'

In [45]:
def solution(cipher, code):
    count = 1
    for i in cipher:
        if count == code:
            print(i)
            count = 0
        count += 1

solution("dfjardstddetckdaccccdegk", 4)

a
t
t
a
c
k


In [46]:
def solution(cipher, code):
    count = 1
    for i, j in enumerate(cipher, 1):
        if i % code == 0:
            print(j)

solution("dfjardstddetckdaccccdegk", 4)

a
t
t
a
c
k


In [50]:
# 3 7 11 15
# 머리아픈 코드
# 이런 풀이는 권하지 않습니다.
def solution(cipher, code):
    result = ''
    for i in range(1, len(cipher) // code + 1):
        result += cipher[i * code - 1]
    return result

solution("dfjardstddetckdaccccdegk", 4)

'attack'

In [52]:
s = 0
for i in range(1, 101):
    s += i
print(s)

# 이건 그냥 수학적인 지식을 자랑하는...
# 별로입니다.
n = 100
s = n * (n + 1) // 2
print(s)

5050
5050


## 5번: 369게임
https://school.programmers.co.kr/learn/courses/30/lessons/120891

In [55]:
def solution(order):
    order = str(order)
    return order.count('3') + order.count('6') + order.count('9')

solution('29423')

2

In [56]:
import re

def solution(order):
    order = str(order)
    return len(list(re.findall(r'[369]', order)))

## 6번: 중복문자 제거
https://school.programmers.co.kr/learn/courses/30/lessons/120888

In [57]:
set("people") # 중복 제거 완료, 그러나 순서를 보장하지 않음!

{'e', 'l', 'o', 'p'}

In [60]:
def solution(s):
    answer = ''
    for i in s:
        if i not in answer:
            answer += i
    return answer

solution('people')

'peol'

In [61]:
# 참 멋진 풀이지만 주니어에겐 어렵다
# 딕셔너리는 키의 중복이 안된다는 점을 이용! dict는 3.6부터 순서를 보장한다.
def solution(my_string):
    return ''.join(dict.fromkeys(my_string))

solution('people')

'peol'

## 7번: A로 B 만들기
https://school.programmers.co.kr/learn/courses/30/lessons/120886

In [70]:
import re

def solution(before, after):
    for i in before:
        if i in before and i
    print(s)

solution("apple", "aplle")

['a', 'p', 'p', 'l', 'e']


In [74]:
# 간단한 답안~... 난 못풀었다.
def solution(before, after):
    if len(before) != len(after): # 예외 처리는 앞에서 반드시 해주어야 합니다. 특히나 요소가 없거나 길이가 0인경우.
        return 0
    return 1 if sorted(before) == sorted(after) else 0

solution("apple", "aplle")

0

In [78]:
# 안배운거니까 Keep
import collections

# collections.Counter("olleh") == collections.Counter("hello")
# collections.Counter("olleh") == collections.Counter("hhhhhhhhhello")
collections.Counter("olleh")

Counter({'o': 1, 'l': 2, 'e': 1, 'h': 1})

In [79]:
collections.Counter("olleh") == collections.Counter("hhhhhhhhhello")

False

`collections` 알아두면 엄청 편함

In [80]:
def solution(before, after):
    a = list(after)
    for i in before:
        if i in a:
            a.remove(i)
        else:
            return 0
    if a: # 이 if문 없어도 통과 되지만 찝찝하니까 놔두자.
        return 0
    return 1

solution("olleh", "hello")

1

In [82]:
# 회문

# 'hello' => 'elloh' => 'llohe'
# 'hello' => 'ohell' => 'lohel'
# collections.deque를 사용해서 풀면 쉽게 풀립니다.

# 더 쉬운방법은 그냥 더해버리기.
# 문제1 'hello'를 앞뒤로 이동시켜 'llohe'를 만들 수 있나요?
# 'hellohello'

# 문제2 몇칸 이동했나요?
# 'hellohello'.index('llohe')

## 8번: 저주의 숫자 3 (좋은문제!)
https://school.programmers.co.kr/learn/courses/30/lessons/120871

In [83]:
# 십진수    3숫자마을
# 1         1
# 2         2
# 3         4
# 4         5
# 5         7
# 6         8
# 7         10
# 8         11
# 9         14
# 10        16

In [84]:
# [True, True, False]...

In [85]:
# filter('3이 들어간 숫자 없애기', filter('3의 배수 없애기', [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]))

In [86]:
list(filter(lambda x: (x % 3 != 0) and ('3' not in str(x)), range(100)))[15-1]

25

In [91]:
# 이거 오답처리됨! 숫자를 충분히 생성해주지 못함.
# 저주의 숫자가 100개 생성되어야 함. range(1000) 정도로 해주자.
def solution(num):
    return list(filter(lambda x: (x % 3 != 0) and ('3' not in str(x)), range(100)))[num-1]

solution(15)

25

In [88]:
def solution(num):
    return list(filter(lambda x: (x % 3 != 0) and ('3' not in str(x)), range(1000)))[num-1]

solution(15)

25

In [90]:
solution = lambda n:[i for i in range(10000) if i % 3 != 0 and '3' not in str(i)][n-1]

In [93]:
def solution(num):
    l = []
    for i in range(1000):
        if i % 3 != 0:
            l.append(i)
        elif '3' not in str(i):
            l.append(i)
    print(l)

solution(15)

[0, 1, 2, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 31, 32, 34, 35, 37, 38, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 124, 125, 126, 127, 128, 129, 130, 131, 133, 134, 136, 137, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 214, 215, 216, 217, 218, 219, 220, 221, 222, 223, 224, 225, 226, 227, 228, 229, 230, 232, 233, 235, 2

## 9번: 진료 순서 정하기 (좋은문제!)
https://school.programmers.co.kr/learn/courses/30/lessons/120835

In [100]:
# emergency     result
# [3, 76, 24]   [3, 1, 2]

def solution(emergency):
    sorted_emergency = sorted(emergency, reverse=True)
    return [sorted_emergency.index(i) + 1 for i in emergency]


solution([3, 76, 24])

[3, 1, 2]

In [101]:
# 좋은 문제입니다.
emergency = [3, 76, 24]

sorted_emergency = sorted(emergency, reverse=True)
sorted_emergency

# 원하는 결과값 [3, 1, 2]
[sorted_emergency.index(i) + 1 for i in emergency]

[3, 1, 2]

In [98]:
# 다른 예시 (좋은방법인것같다!)
data = ['제주', '경기', '전주']
data2 = {
    '제주': '064', # 그냥 064로 쓰면 진법으로 인식해서 에러가 날수도있음.
    '경기': '031',
    '전주': '063'
}

[data2[i] for i in data]

['064', '031', '063']

## 10번: 가까운 수 (좋은문제!)
https://school.programmers.co.kr/learn/courses/30/lessons/120890

In [110]:
# 이것도 정렬 문제다.

In [105]:
l = [3, 10, 28]
sorted(l, key=lambda x: abs(x-20))[0]

28

In [106]:
# 오류
# 가까운 값이 여러개 있을 경우 더 작은값을 반환해줘야 한다.
def solution(array, n):
    return sorted(array, key=lambda x: abs(x-n))[0]

array와 list는 다릅니다! 파이썬에서는 array가 없어요.  
array를 연결리스트를 이용해서 만든게 => list  
(위 예제의 array는 그냥 변구명임)

In [108]:
# [3, 10, 28, 30, 12] => [17, 10, 8, 10, 8]
# [3, 10, 28, 30, 12] => [(17, 3), (10, 10), (8, 28), (10, 30), (8, 12)]
# 원하는 숫자: 20
# result: 28

array = [3, 10, 28, 30, 12]
n = 20

28 - 20 == 8
12 - 20 == -8

20 - 28 == -8
20 - 12 == 8

# 정답: 작은 수 반환
sorted(array, key=lambda x:(abs(x-n), x))[0]

# 더 큰 수를 반환하고 싶다면?
sorted(array, key=lambda x:(abs(x-n), n-x))[0] # 팁, n-x이거나 x-n 2개 중에 하나입니다.

28

In [109]:
# 결론! 정답은 이거
def solution(array, n):
    return sorted(array, key=lambda x:(abs(x-n), x))[0]

## 11번: k의 개수
https://school.programmers.co.kr/learn/courses/30/lessons/120887

In [113]:
# i    j    k
# 1    13    1

i = 1
j = 13
k = 1

str(list(range(i, j+1)))
'[1, 2, 3]'.count(',') # 출력: 2

str(list(range(i, j+1))).count(str(k))

6

밑에는 `swap`꿀팁 ㅎㅎ

In [115]:
a = 10
b = 20

# swap (다른 언어에서)
temp = a
a = b
b = temp

# python에서 사용하는 swap
a = 10
b = 20
a, b = b, a
a, b

(20, 10)

In [122]:
i = 1
j = 13
k = 1

count = 0
for temp in range(i, j): # temp라는 변수도 사실 실무에서는 권장하지 않음.
    count += (str(temp).count(str(k)))
count

5

In [123]:
# 최종 답안
def solution(i, j, k):
    return str(list(range(i, j+1))).count(str(k))

## 겹치는 선분의 길이 문제는 어려워서 pass

# 강사님 직접 출제 문제

In [126]:
# 각 선분이 있는 곳에 총 길이 합을 구하라
# [[0, 5], [3, 5], [7, 10]]

선 = [False] * 10
선

[False, False, False, False, False, False, False, False, False, False]

In [127]:
for i in range(0, 5):
    선[i] = True
선

[True, True, True, True, True, False, False, False, False, False]

In [128]:
for i in range(3, 5):
    선[i] = True

In [129]:
for i in range(7, 10):
    선[i] = True

In [130]:
sum(선)

8

In [142]:
# 에라토스테네스의 체 => 소수판별 => 이것을 알고리즘 문제로 내는 것은 저는 반대
소수 = [True] * 120
소수[0] = 소수[1] = False

for i in range(4, 120, 2):
    소수[i] = False

for i in range(6, 120, 3):
    소수[i] = False

# 4는 2의 배수에 속하기 때문에 할 필요가 없습니다.
# 그래서 언제까지?
# 11 ** 2 <= 120 이기 때문에

링크: https://nahwasa.com/entry/%EC%97%90%EB%9D%BC%ED%86%A0%EC%8A%A4%ED%85%8C%EB%84%A4%EC%8A%A4%EC%9D%98-%EC%B2%B4-%ED%98%B9%EC%9D%80-%EC%86%8C%EC%88%98%ED%8C%90%EC%A0%95-%EC%8B%9C-%EC%A0%9C%EA%B3%B1%EA%B7%BC-%EA%B9%8C%EC%A7%80%EB%A7%8C-%ED%99%95%EC%9D%B8%ED%95%98%EB%A9%B4-%EB%90%98%EB%8A%94-%EC%9D%B4%EC%9C%A0

In [143]:
# 소수라는게 다 확정이 되고 나면,
for 소수, 판별 in enumerate(소수):
    if 판별:
        print(소수)

2
3
5
7
11
13
17
19
23
25
29
31
35
37
41
43
47
49
53
55
59
61
65
67
71
73
77
79
83
85
89
91
95
97
101
103
107
109
113
115
119


# 파이알고 문제
https://100.pyalgo.co.kr/?page=23

In [144]:
# 행렬의 연산과 같은 것은 np를 사용하시면 쉽고 빠르게 풀 수 있습니다.
import numpy as np

x = np.array([1, 2, 3])
x * 2

array([2, 4, 6])

In [147]:
# 정말 많이 씁니다!
s = [[1, 3, 5], [7, 9, 11], [13, 15, 17]]
s = np.array(s)
행, 렬 = np.where(s == 7)
행

array([1])

In [152]:
# 지뢰찾기
x = [[0, 1, 0, 0],
     [0, 1, 0, 0],
     [0, 0, 0, 1]]

x = np.array(x)
np.where(x == 1)

(array([0, 1, 2]), array([1, 1, 3]))

In [151]:
x = [[0, 1, 0, 0],
     [0, 1, 0, 0],
     [0, 0, 0, 1]]

s = 0
for i in x:
    s += i.count(1)

s

3

In [155]:
# True, False로 반환받기

x = [[0, 1, 0, 0],
     [0, 1, 0, 0],
     [0, 0, 0, 1]]

x = np.array(x)
x == 1

array([[False,  True, False, False],
       [False,  True, False, False],
       [False, False, False,  True]])

In [156]:
x = [[0, 5, 2, 0],
     [0, 7, 0, 6],
     [0, 1, 3, 5]]

x = np.array(x)
x > 3

array([[False,  True, False, False],
       [False,  True, False,  True],
       [False, False, False,  True]])